# Generated by Django 2.0.4 on 2019-01-01 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosjh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diarydetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('content', models.CharField(default='休息', max_length=1000, verbose_name='事项')),
                ('M_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosjh.Member', verbose_name='江湖名')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['stop_time'], 'verbose_name': '日程', 'verbose_name_plural': '日程'},
        ),
    ]
