# Generated by Django 2.0.4 on 2019-01-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosjh', '0002_auto_20190101_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarydetail',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='日记内容'),
        ),
        migrations.AlterField(
            model_name='diarydetail',
            name='pubtime',
            field=models.DateField(blank=True, null=True, verbose_name='发布日期'),
        ),
    ]
