# Generated by Django 2.0.4 on 2019-01-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosjh', '0004_auto_20190102_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarydetail',
            name='type',
            field=models.CharField(default='个人日记', max_length=16, verbose_name='类型'),
        ),
    ]
